INSERT INTO workforce_diversity (
    employee_id, department, job_role, job_level, location, employment_type,
    joining_date, tenure_band, age_band, gender_category,
    workforce_diversity_category, salary_band, annual_compensation_lpa,
    performance_rating, promotion_status, promotion_eligibility,
    leadership_position, training_hours, engagement_score,
    inclusion_score, belonging_score, manager_support_score,
    psychological_safety_score, recognition_count,
    career_opportunity_score, internal_mobility, attrition_status,
    attrition_type, exit_reason, hiring_source, review_period,
    inclusion_index
) VALUES
(
    'EMP-0001',
    'Sales',
    'Sales Executive',
    'Senior',
    'Bengaluru',
    'Full-Time',
    '2019-03-10',
    '5-10 Years',
    '25-34',
    'Female',
    'Category B',
    '10-15 LPA',
    14.21,
    3,
    'No',
    'Yes',
    'No',
    11,
    82.57,
    75.99,
    66.62,
    67.87,
    75.71,
    5,
    72.46,
    'No',
    'No',
    'None',
    'None',
    'Company Careers',
    '2024-Q3',
    75.03
);