CREATE TABLE IF NOT EXISTS workforce_diversity (
    employee_id VARCHAR(20) PRIMARY KEY,
    department VARCHAR(50),
    job_role VARCHAR(100),
    job_level VARCHAR(30),
    location VARCHAR(50),
    employment_type VARCHAR(30),
    joining_date DATE,
    tenure_band VARCHAR(30),
    age_band VARCHAR(20),
    gender_category VARCHAR(30),
    workforce_diversity_category VARCHAR(40),
    salary_band VARCHAR(30),
    annual_compensation_lpa DECIMAL(10,2),
    performance_rating INT,
    promotion_status VARCHAR(10),
    promotion_eligibility VARCHAR(10),
    leadership_position VARCHAR(10),
    training_hours INT,
    engagement_score DECIMAL(5,2),
    inclusion_score DECIMAL(5,2),
    belonging_score DECIMAL(5,2),
    manager_support_score DECIMAL(5,2),
    psychological_safety_score DECIMAL(5,2),
    recognition_count INT,
    career_opportunity_score DECIMAL(5,2),
    internal_mobility VARCHAR(10),
    attrition_status VARCHAR(10),
    attrition_type VARCHAR(30),
    exit_reason VARCHAR(100),
    hiring_source VARCHAR(50),
    review_period VARCHAR(20),
    inclusion_index DECIMAL(5,2)
);